use_frameworks!

target 'GridView_Example' do
  pod 'GridView', :path => '../'

  target 'GridView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
